name: Manual URL Checker

on:
  workflow_dispatch: 


permissions:
  contents: write

jobs:
  run-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14.3'

      - name: Install Dependencies
        run: pip install httpx

      - name: Run URL Script

        run: python engine/urlScript.py > report.txt

      - name: Save Results as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: liveness-report
          path: report.txt

      - name: Commit and Push api.json
        run: |

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          

          git add api.json
          


          if git diff --staged --quiet; then
            echo "No changes in api.json. Skipping push."
          else
            git commit -m "Auto-update api.json [skip ci]"
            git push
          fi